env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - off
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
